//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Valheim : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean ToggleInventory
        {
            get
            {
                return SteamVR_Actions.valheim_ToggleInventory;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleMenu
        {
            get
            {
                return SteamVR_Actions.valheim_ToggleMenu;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Walk
        {
            get
            {
                return SteamVR_Actions.valheim_Walk;
            }
        }
        
        public virtual SteamVR_Action_Boolean Attack
        {
            get
            {
                return SteamVR_Actions.valheim_Attack;
            }
        }
        
        public virtual SteamVR_Action_Boolean SecondaryAttack
        {
            get
            {
                return SteamVR_Actions.valheim_SecondaryAttack;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.valheim_Jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean Block
        {
            get
            {
                return SteamVR_Actions.valheim_Block;
            }
        }
        
        public virtual SteamVR_Action_Boolean Crouch
        {
            get
            {
                return SteamVR_Actions.valheim_Crouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Run
        {
            get
            {
                return SteamVR_Actions.valheim_Run;
            }
        }
        
        public virtual SteamVR_Action_Boolean Use
        {
            get
            {
                return SteamVR_Actions.valheim_Use;
            }
        }
        
        public virtual SteamVR_Action_Boolean Hide
        {
            get
            {
                return SteamVR_Actions.valheim_Hide;
            }
        }
        
        public virtual SteamVR_Action_Boolean Sit
        {
            get
            {
                return SteamVR_Actions.valheim_Sit;
            }
        }
        
        public virtual SteamVR_Action_Boolean GPower
        {
            get
            {
                return SteamVR_Actions.valheim_GPower;
            }
        }
        
        public virtual SteamVR_Action_Vector2 PitchAndYaw
        {
            get
            {
                return SteamVR_Actions.valheim_PitchAndYaw;
            }
        }
        
        public virtual SteamVR_Action_Pose PoseL
        {
            get
            {
                return SteamVR_Actions.valheim_PoseL;
            }
        }
        
        public virtual SteamVR_Action_Pose PoseR
        {
            get
            {
                return SteamVR_Actions.valheim_PoseR;
            }
        }
        
        public virtual SteamVR_Action_Boolean HotbarUp
        {
            get
            {
                return SteamVR_Actions.valheim_HotbarUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean HotbarDown
        {
            get
            {
                return SteamVR_Actions.valheim_HotbarDown;
            }
        }
        
        public virtual SteamVR_Action_Vector2 HotbarScroll
        {
            get
            {
                return SteamVR_Actions.valheim_HotbarScroll;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleMap
        {
            get
            {
                return SteamVR_Actions.valheim_ToggleMap;
            }
        }
        
        public virtual SteamVR_Action_Boolean HotbarUse
        {
            get
            {
                return SteamVR_Actions.valheim_HotbarUse;
            }
        }
        
        public virtual SteamVR_Action_Vector2 ContextScroll
        {
            get
            {
                return SteamVR_Actions.valheim_ContextScroll;
            }
        }
    }
}
