//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_LaserPointers : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean LeftClick
        {
            get
            {
                return SteamVR_Actions.laserPointers_LeftClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightClick
        {
            get
            {
                return SteamVR_Actions.laserPointers_RightClick;
            }
        }
    }
}
