//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Valheim : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean ToggleInventory
        {
            get
            {
                return SteamVR_Actions.valheim_ToggleInventory;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleMenu
        {
            get
            {
                return SteamVR_Actions.valheim_ToggleMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.valheim_Jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean Use
        {
            get
            {
                return SteamVR_Actions.valheim_Use;
            }
        }
        
        public virtual SteamVR_Action_Boolean Sit
        {
            get
            {
                return SteamVR_Actions.valheim_Sit;
            }
        }
        
        public virtual SteamVR_Action_Vector2 PitchAndYaw
        {
            get
            {
                return SteamVR_Actions.valheim_PitchAndYaw;
            }
        }
        
        public virtual SteamVR_Action_Pose PoseL
        {
            get
            {
                return SteamVR_Actions.valheim_PoseL;
            }
        }
        
        public virtual SteamVR_Action_Pose PoseR
        {
            get
            {
                return SteamVR_Actions.valheim_PoseR;
            }
        }
        
        public virtual SteamVR_Action_Pose BodyPose
        {
            get
            {
                return SteamVR_Actions.valheim_BodyPose;
            }
        }
        
        public virtual SteamVR_Action_Boolean HotbarUp
        {
            get
            {
                return SteamVR_Actions.valheim_HotbarUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean HotbarDown
        {
            get
            {
                return SteamVR_Actions.valheim_HotbarDown;
            }
        }
        
        public virtual SteamVR_Action_Vector2 HotbarScroll
        {
            get
            {
                return SteamVR_Actions.valheim_HotbarScroll;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleMap
        {
            get
            {
                return SteamVR_Actions.valheim_ToggleMap;
            }
        }
        
        public virtual SteamVR_Action_Boolean HotbarUse
        {
            get
            {
                return SteamVR_Actions.valheim_HotbarUse;
            }
        }
        
        public virtual SteamVR_Action_Vector2 ContextScroll
        {
            get
            {
                return SteamVR_Actions.valheim_ContextScroll;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.valheim_Grab;
            }
        }
        
        public virtual SteamVR_Action_Boolean QuickSwitch
        {
            get
            {
                return SteamVR_Actions.valheim_QuickSwitch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Walk
        {
            get
            {
                return SteamVR_Actions.valheim_Walk;
            }
        }
        
        public virtual SteamVR_Action_Boolean QuickActions
        {
            get
            {
                return SteamVR_Actions.valheim_QuickActions;
            }
        }
        
        public virtual SteamVR_Action_Boolean StopGesturedLocomotion
        {
            get
            {
                return SteamVR_Actions.valheim_StopGesturedLocomotion;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleRun
        {
            get
            {
                return SteamVR_Actions.valheim_ToggleRun;
            }
        }
        
        public virtual SteamVR_Action_Boolean HoldRun
        {
            get
            {
                return SteamVR_Actions.valheim_HoldRun;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleCrouch
        {
            get
            {
                return SteamVR_Actions.valheim_ToggleCrouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Dodge
        {
            get
            {
                return SteamVR_Actions.valheim_Dodge;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleAutoPickup
        {
            get
            {
                return SteamVR_Actions.valheim_ToggleAutoPickup;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightClick
        {
            get
            {
                return SteamVR_Actions.valheim_RightClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftClick
        {
            get
            {
                return SteamVR_Actions.valheim_LeftClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean AddMapPin
        {
            get
            {
                return SteamVR_Actions.valheim_AddMapPin;
            }
        }
        
        public virtual SteamVR_Action_Boolean MiddleClick
        {
            get
            {
                return SteamVR_Actions.valheim_MiddleClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean DiscardItem
        {
            get
            {
                return SteamVR_Actions.valheim_DiscardItem;
            }
        }
        
        public virtual SteamVR_Action_Boolean SplitStack
        {
            get
            {
                return SteamVR_Actions.valheim_SplitStack;
            }
        }
        
        public virtual SteamVR_Action_Boolean ScrollUp
        {
            get
            {
                return SteamVR_Actions.valheim_ScrollUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean ScrollDown
        {
            get
            {
                return SteamVR_Actions.valheim_ScrollDown;
            }
        }

        public virtual SteamVR_Action_Boolean RemovePiece
        {
            get
            {
                return SteamVR_Actions.valheim_RemovePiece;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.valheim_Haptic;
            }
        }
    }
}
