//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_default_InteractUI;
        
        private static SteamVR_Action_Boolean p_default_Teleport;
        
        private static SteamVR_Action_Boolean p_default_GrabPinch;
        
        private static SteamVR_Action_Boolean p_default_GrabGrip;
        
        private static SteamVR_Action_Pose p_default_Pose;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonRightHand;
        
        private static SteamVR_Action_Single p_default_Squeeze;
        
        private static SteamVR_Action_Boolean p_default_HeadsetOnHead;
        
        private static SteamVR_Action_Vibration p_default_Haptic;
        
        private static SteamVR_Action_Boolean p_valheim_ToggleInventory;
        
        private static SteamVR_Action_Boolean p_valheim_ToggleMenu;
        
        private static SteamVR_Action_Boolean p_valheim_Jump;
        
        private static SteamVR_Action_Boolean p_valheim_Use;
        
        private static SteamVR_Action_Boolean p_valheim_Sit;
        
        private static SteamVR_Action_Vector2 p_valheim_PitchAndYaw;
        
        private static SteamVR_Action_Pose p_valheim_PoseL;
        
        private static SteamVR_Action_Pose p_valheim_PoseR;
        
        private static SteamVR_Action_Boolean p_valheim_HotbarUp;
        
        private static SteamVR_Action_Boolean p_valheim_HotbarDown;
        
        private static SteamVR_Action_Vector2 p_valheim_HotbarScroll;
        
        private static SteamVR_Action_Boolean p_valheim_ToggleMap;
        
        private static SteamVR_Action_Boolean p_valheim_HotbarUse;
        
        private static SteamVR_Action_Vector2 p_valheim_ContextScroll;
        
        private static SteamVR_Action_Boolean p_valheim_Grab;
        
        private static SteamVR_Action_Boolean p_valheim_QuickSwitch;
        
        private static SteamVR_Action_Vector2 p_valheim_Walk;
        
        private static SteamVR_Action_Boolean p_valheim_UseLeft;
        
        private static SteamVR_Action_Boolean p_valheim_QuickActions;
        
        private static SteamVR_Action_Boolean p_valheim_StopGesturedLocomotion;
        
        private static SteamVR_Action_Vibration p_valheim_Haptic;
        
        private static SteamVR_Action_Boolean p_laserPointers_LeftClick;
        
        private static SteamVR_Action_Boolean p_laserPointers_RightClick;
        
        private static SteamVR_Action_Boolean p_laserPointers_ClickModifier;
        
        private static SteamVR_Action_Boolean p_laserPointers_Jump;
        
        private static SteamVR_Action_Vector2 p_laserPointers_PitchAndYaw;
        
        public static SteamVR_Action_Boolean default_InteractUI
        {
            get
            {
                return SteamVR_Actions.p_default_InteractUI.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Teleport
        {
            get
            {
                return SteamVR_Actions.p_default_Teleport.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabPinch
        {
            get
            {
                return SteamVR_Actions.p_default_GrabPinch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabGrip
        {
            get
            {
                return SteamVR_Actions.p_default_GrabGrip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose default_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonLeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonRightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Single default_Squeeze
        {
            get
            {
                return SteamVR_Actions.p_default_Squeeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean default_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_default_HeadsetOnHead.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration default_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Boolean valheim_ToggleInventory
        {
            get
            {
                return SteamVR_Actions.p_valheim_ToggleInventory.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean valheim_ToggleMenu
        {
            get
            {
                return SteamVR_Actions.p_valheim_ToggleMenu.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean valheim_Jump
        {
            get
            {
                return SteamVR_Actions.p_valheim_Jump.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean valheim_Use
        {
            get
            {
                return SteamVR_Actions.p_valheim_Use.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean valheim_Sit
        {
            get
            {
                return SteamVR_Actions.p_valheim_Sit.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 valheim_PitchAndYaw
        {
            get
            {
                return SteamVR_Actions.p_valheim_PitchAndYaw.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Pose valheim_PoseL
        {
            get
            {
                return SteamVR_Actions.p_valheim_PoseL.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Pose valheim_PoseR
        {
            get
            {
                return SteamVR_Actions.p_valheim_PoseR.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Boolean valheim_HotbarUp
        {
            get
            {
                return SteamVR_Actions.p_valheim_HotbarUp.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean valheim_HotbarDown
        {
            get
            {
                return SteamVR_Actions.p_valheim_HotbarDown.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 valheim_HotbarScroll
        {
            get
            {
                return SteamVR_Actions.p_valheim_HotbarScroll.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean valheim_ToggleMap
        {
            get
            {
                return SteamVR_Actions.p_valheim_ToggleMap.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean valheim_HotbarUse
        {
            get
            {
                return SteamVR_Actions.p_valheim_HotbarUse.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 valheim_ContextScroll
        {
            get
            {
                return SteamVR_Actions.p_valheim_ContextScroll.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean valheim_Grab
        {
            get
            {
                return SteamVR_Actions.p_valheim_Grab.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean valheim_QuickSwitch
        {
            get
            {
                return SteamVR_Actions.p_valheim_QuickSwitch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 valheim_Walk
        {
            get
            {
                return SteamVR_Actions.p_valheim_Walk.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean valheim_UseLeft
        {
            get
            {
                return SteamVR_Actions.p_valheim_UseLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean valheim_QuickActions
        {
            get
            {
                return SteamVR_Actions.p_valheim_QuickActions.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean valheim_StopGesturedLocomotion
        {
            get
            {
                return SteamVR_Actions.p_valheim_StopGesturedLocomotion.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration valheim_Haptic
        {
            get
            {
                return SteamVR_Actions.p_valheim_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Boolean laserPointers_LeftClick
        {
            get
            {
                return SteamVR_Actions.p_laserPointers_LeftClick.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean laserPointers_RightClick
        {
            get
            {
                return SteamVR_Actions.p_laserPointers_RightClick.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean laserPointers_ClickModifier
        {
            get
            {
                return SteamVR_Actions.p_laserPointers_ClickModifier.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean laserPointers_Jump
        {
            get
            {
                return SteamVR_Actions.p_laserPointers_Jump.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 laserPointers_PitchAndYaw
        {
            get
            {
                return SteamVR_Actions.p_laserPointers_PitchAndYaw.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.valheim_ToggleInventory,
                    SteamVR_Actions.valheim_ToggleMenu,
                    SteamVR_Actions.valheim_Jump,
                    SteamVR_Actions.valheim_Use,
                    SteamVR_Actions.valheim_Sit,
                    SteamVR_Actions.valheim_PitchAndYaw,
                    SteamVR_Actions.valheim_PoseL,
                    SteamVR_Actions.valheim_PoseR,
                    SteamVR_Actions.valheim_HotbarUp,
                    SteamVR_Actions.valheim_HotbarDown,
                    SteamVR_Actions.valheim_HotbarScroll,
                    SteamVR_Actions.valheim_ToggleMap,
                    SteamVR_Actions.valheim_HotbarUse,
                    SteamVR_Actions.valheim_ContextScroll,
                    SteamVR_Actions.valheim_Grab,
                    SteamVR_Actions.valheim_QuickSwitch,
                    SteamVR_Actions.valheim_Walk,
                    SteamVR_Actions.valheim_UseLeft,
                    SteamVR_Actions.valheim_QuickActions,
                    SteamVR_Actions.valheim_StopGesturedLocomotion,
                    SteamVR_Actions.valheim_Haptic,
                    SteamVR_Actions.laserPointers_LeftClick,
                    SteamVR_Actions.laserPointers_RightClick,
                    SteamVR_Actions.laserPointers_ClickModifier,
                    SteamVR_Actions.laserPointers_Jump,
                    SteamVR_Actions.laserPointers_PitchAndYaw};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.valheim_ToggleInventory,
                    SteamVR_Actions.valheim_ToggleMenu,
                    SteamVR_Actions.valheim_Jump,
                    SteamVR_Actions.valheim_Use,
                    SteamVR_Actions.valheim_Sit,
                    SteamVR_Actions.valheim_PitchAndYaw,
                    SteamVR_Actions.valheim_PoseL,
                    SteamVR_Actions.valheim_PoseR,
                    SteamVR_Actions.valheim_HotbarUp,
                    SteamVR_Actions.valheim_HotbarDown,
                    SteamVR_Actions.valheim_HotbarScroll,
                    SteamVR_Actions.valheim_ToggleMap,
                    SteamVR_Actions.valheim_HotbarUse,
                    SteamVR_Actions.valheim_ContextScroll,
                    SteamVR_Actions.valheim_Grab,
                    SteamVR_Actions.valheim_QuickSwitch,
                    SteamVR_Actions.valheim_Walk,
                    SteamVR_Actions.valheim_UseLeft,
                    SteamVR_Actions.valheim_QuickActions,
                    SteamVR_Actions.valheim_StopGesturedLocomotion,
                    SteamVR_Actions.laserPointers_LeftClick,
                    SteamVR_Actions.laserPointers_RightClick,
                    SteamVR_Actions.laserPointers_ClickModifier,
                    SteamVR_Actions.laserPointers_Jump,
                    SteamVR_Actions.laserPointers_PitchAndYaw};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.valheim_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.valheim_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.valheim_PoseL,
                    SteamVR_Actions.valheim_PoseR};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.valheim_ToggleInventory,
                    SteamVR_Actions.valheim_ToggleMenu,
                    SteamVR_Actions.valheim_Jump,
                    SteamVR_Actions.valheim_Use,
                    SteamVR_Actions.valheim_Sit,
                    SteamVR_Actions.valheim_HotbarUp,
                    SteamVR_Actions.valheim_HotbarDown,
                    SteamVR_Actions.valheim_ToggleMap,
                    SteamVR_Actions.valheim_HotbarUse,
                    SteamVR_Actions.valheim_Grab,
                    SteamVR_Actions.valheim_QuickSwitch,
                    SteamVR_Actions.valheim_UseLeft,
                    SteamVR_Actions.valheim_QuickActions,
                    SteamVR_Actions.valheim_StopGesturedLocomotion,
                    SteamVR_Actions.laserPointers_LeftClick,
                    SteamVR_Actions.laserPointers_RightClick,
                    SteamVR_Actions.laserPointers_ClickModifier,
                    SteamVR_Actions.laserPointers_Jump};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.default_Squeeze};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.valheim_PitchAndYaw,
                    SteamVR_Actions.valheim_HotbarScroll,
                    SteamVR_Actions.valheim_ContextScroll,
                    SteamVR_Actions.valheim_Walk,
                    SteamVR_Actions.laserPointers_PitchAndYaw};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.valheim_ToggleInventory,
                    SteamVR_Actions.valheim_ToggleMenu,
                    SteamVR_Actions.valheim_Jump,
                    SteamVR_Actions.valheim_Use,
                    SteamVR_Actions.valheim_Sit,
                    SteamVR_Actions.valheim_PitchAndYaw,
                    SteamVR_Actions.valheim_HotbarUp,
                    SteamVR_Actions.valheim_HotbarDown,
                    SteamVR_Actions.valheim_HotbarScroll,
                    SteamVR_Actions.valheim_ToggleMap,
                    SteamVR_Actions.valheim_HotbarUse,
                    SteamVR_Actions.valheim_ContextScroll,
                    SteamVR_Actions.valheim_Grab,
                    SteamVR_Actions.valheim_QuickSwitch,
                    SteamVR_Actions.valheim_Walk,
                    SteamVR_Actions.valheim_UseLeft,
                    SteamVR_Actions.valheim_QuickActions,
                    SteamVR_Actions.valheim_StopGesturedLocomotion,
                    SteamVR_Actions.laserPointers_LeftClick,
                    SteamVR_Actions.laserPointers_RightClick,
                    SteamVR_Actions.laserPointers_ClickModifier,
                    SteamVR_Actions.laserPointers_Jump,
                    SteamVR_Actions.laserPointers_PitchAndYaw};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_InteractUI = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/InteractUI")));
            SteamVR_Actions.p_default_Teleport = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Teleport")));
            SteamVR_Actions.p_default_GrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabPinch")));
            SteamVR_Actions.p_default_GrabGrip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabGrip")));
            SteamVR_Actions.p_default_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/Pose")));
            SteamVR_Actions.p_default_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonLeftHand")));
            SteamVR_Actions.p_default_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonRightHand")));
            SteamVR_Actions.p_default_Squeeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default/in/Squeeze")));
            SteamVR_Actions.p_default_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/HeadsetOnHead")));
            SteamVR_Actions.p_default_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/default/out/Haptic")));
            SteamVR_Actions.p_valheim_ToggleInventory = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Valheim/in/ToggleInventory")));
            SteamVR_Actions.p_valheim_ToggleMenu = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Valheim/in/ToggleMenu")));
            SteamVR_Actions.p_valheim_Jump = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Valheim/in/Jump")));
            SteamVR_Actions.p_valheim_Use = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Valheim/in/Use")));
            SteamVR_Actions.p_valheim_Sit = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Valheim/in/Sit")));
            SteamVR_Actions.p_valheim_PitchAndYaw = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/Valheim/in/PitchAndYaw")));
            SteamVR_Actions.p_valheim_PoseL = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/Valheim/in/PoseL")));
            SteamVR_Actions.p_valheim_PoseR = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/Valheim/in/PoseR")));
            SteamVR_Actions.p_valheim_HotbarUp = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Valheim/in/HotbarUp")));
            SteamVR_Actions.p_valheim_HotbarDown = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Valheim/in/HotbarDown")));
            SteamVR_Actions.p_valheim_HotbarScroll = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/Valheim/in/HotbarScroll")));
            SteamVR_Actions.p_valheim_ToggleMap = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Valheim/in/ToggleMap")));
            SteamVR_Actions.p_valheim_HotbarUse = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Valheim/in/HotbarUse")));
            SteamVR_Actions.p_valheim_ContextScroll = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/Valheim/in/ContextScroll")));
            SteamVR_Actions.p_valheim_Grab = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Valheim/in/Grab")));
            SteamVR_Actions.p_valheim_QuickSwitch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Valheim/in/QuickSwitch")));
            SteamVR_Actions.p_valheim_Walk = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/Valheim/in/Walk")));
            SteamVR_Actions.p_valheim_UseLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Valheim/in/UseLeft")));
            SteamVR_Actions.p_valheim_QuickActions = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Valheim/in/QuickActions")));
            SteamVR_Actions.p_valheim_StopGesturedLocomotion = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Valheim/in/StopGesturedLocomotion")));
            SteamVR_Actions.p_valheim_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/Valheim/out/Haptic")));
            SteamVR_Actions.p_laserPointers_LeftClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/LaserPointers/in/LeftClick")));
            SteamVR_Actions.p_laserPointers_RightClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/LaserPointers/in/RightClick")));
            SteamVR_Actions.p_laserPointers_ClickModifier = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/LaserPointers/in/ClickModifier")));
            SteamVR_Actions.p_laserPointers_Jump = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/LaserPointers/in/Jump")));
            SteamVR_Actions.p_laserPointers_PitchAndYaw = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/LaserPointers/in/PitchAndYaw")));
        }
    }
}
